run:
  version: "2"
  timeout: 3m
  tests: true
  go: '1.25'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck
    - bodyclose
    - unparam
    - gocritic
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
        - errcheck
